# Color variables
export COLOR_NONE="0"

export COLOR_BLACK="0;30"
export COLOR_RED="0;31"
export COLOR_GREEN="0;32"
export COLOR_ORANGE="0;33"
export COLOR_BLUE="0;34"
export COLOR_PURPLE="0;35"
export COLOR_CYAN="0;36"
export COLOR_GRAY_LIGHT="0;37"

export COLOR_GRAY_DARK="1;30"
export COLOR_RED_LIGHT="1;31"
export COLOR_GREEN_LIGHT="1;32"
export COLOR_YELLOW="1;33"
export COLOR_BLUE_LIGHT="1;34"
export COLOR_PURPLE_LIGHT="1;35"
export COLOR_CYAN_LIGHT="1;36"
export COLOR_WHITE="1;37"

export ECHO_COLOR_PREFIX='\033['
export ECHO_COLOR_SUFFIX='m'

export ECHO_COLOR_NONE="${ECHO_COLOR_PREFIX}${COLOR_NONE}${ECHO_COLOR_SUFFIX}"

export ECHO_COLOR_BLACK="${ECHO_COLOR_PREFIX}${COLOR_BLACK}${ECHO_COLOR_SUFFIX}"
export ECHO_COLOR_RED="${ECHO_COLOR_PREFIX}${COLOR_RED}${ECHO_COLOR_SUFFIX}"
export ECHO_COLOR_GREEN="${ECHO_COLOR_PREFIX}${COLOR_GREEN}${ECHO_COLOR_SUFFIX}"
export ECHO_COLOR_ORANGE="${ECHO_COLOR_PREFIX}${COLOR_ORANGE}${ECHO_COLOR_SUFFIX}"
export ECHO_COLOR_BLUE="${ECHO_COLOR_PREFIX}${COLOR_BLUE}${ECHO_COLOR_SUFFIX}"
export ECHO_COLOR_PURPLE="${ECHO_COLOR_PREFIX}${COLOR_PURPLE}${ECHO_COLOR_SUFFIX}"
export ECHO_COLOR_CYAN="${ECHO_COLOR_PREFIX}${COLOR_CYAN}${ECHO_COLOR_SUFFIX}"
export ECHO_COLOR_GRAY_LIGHT="${ECHO_COLOR_PREFIX}${COLOR_GRAY_LIGHT}${ECHO_COLOR_SUFFIX}"

export ECHO_COLOR_GRAY_DARK="${ECHO_COLOR_PREFIX}${COLOR_GRAY_DARK}${ECHO_COLOR_SUFFIX}"
export ECHO_COLOR_RED_LIGHT="${ECHO_COLOR_PREFIX}${COLOR_RED_LIGHT}${ECHO_COLOR_SUFFIX}"
export ECHO_COLOR_GREEN_LIGHT="${ECHO_COLOR_PREFIX}${COLOR_GREEN_LIGHT}${ECHO_COLOR_SUFFIX}"
export ECHO_COLOR_YELLOW="${ECHO_COLOR_PREFIX}${COLOR_YELLOW}${ECHO_COLOR_SUFFIX}"
export ECHO_COLOR_BLUE_LIGHT="${ECHO_COLOR_PREFIX}${COLOR_BLUE_LIGHT}${ECHO_COLOR_SUFFIX}"
export ECHO_COLOR_PURPLE_LIGHT="${ECHO_COLOR_PREFIX}${COLOR_PURPLE_LIGHT}${ECHO_COLOR_SUFFIX}"
export ECHO_COLOR_CYAN_LIGHT="${ECHO_COLOR_PREFIX}${COLOR_CYAN_LIGHT}${ECHO_COLOR_SUFFIX}"
export ECHO_COLOR_WHITE="${ECHO_COLOR_PREFIX}${COLOR_WHITE}${ECHO_COLOR_SUFFIX}"
